# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

markdown:            kramdown
highlighter:         rouge

# Setup
title:               狂来论剑
tagline:             '狂来论剑，醉去吟诗'
description:         '狂来论剑，醉去吟诗'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              AntSworD
  email:             zhengjj.asd@gmail.com
  github:            AntSworD

github:
  repo:              https://github.com/AntSworD/antsword.github.io

# Custom vars
version:             1.0.0
